quarkus.http.port=8081
pemsion.sw=27662.77
pension.tw=250629.66
pemsion.hl=187915
pension.state=12570
savings.ajb=7947.52
savings.isa=7036.00
tax.allowance=12570
age.starting=60
spemding=30000.00
income.other=0
mortgage=59514.31

calc.value1=12.345
calc.value2=7.89
pension.default-growth-rate=0.06
mortgage.default-interest-rate=0.04

test.quarkus.http.port=0
quarkus.http.test-port=0