# Disable auth entirely during tests
quarkus.http.auth.permission.protected.paths=/*
quarkus.http.auth.permission.protected.policy=permit
quarkus.http.auth.permission.protected.methods=GET,POST

# No login page in tests
quarkus.http.auth.form.enabled=false

# Disable Elytron user file loading
quarkus.security.users.file.enabled=false
